[package]
name = "magiclist"
version = "0.1.0"
edition = "2021"
description = "List with O(log n) random access, insertion, splitting, and merging"
license = "GPL-3.0-only"

[dependencies]

[profile.release]
debug = true

[dev-dependencies]
rand = "0.8.5"
rand_chacha = "0.3.1"